#!/usr/bin/env python

from view import DisassembleView
import sys
import os

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print "usage: %s program" % sys.argv[0]
        sys.exit(1)

    filepath = os.path.abspath(sys.argv[1])

    if os.path.isfile(filepath):
        DisassembleView(filepath).main()
    else:
        print "[-] There is no file: %s" % (filepath)
